backend/cart/urls.py
from django.urls import path
from .views import CartView, CartAddView, CartRemoveView

app_name = 'cart'

urlpatterns = [
    path('cart/', CartView.as_view(), name='cart'),
    path('cart_add/<int:product_id>/', CartAddView.as_view(), name='cart_add'),
    path('cart_remove/<int:product_id>/', CartRemoveView.as_view(), name='cart_remove'),
]

backend/config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('homepages/', include('homepages.urls', namespace='homepages')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = views.page_not_found
handler403 = views.csrf_failure
handler500 = views.server_error
handler400 = views.bad_request

backend/orders/urls.py
from django.urls import path
from .views import OrdersView, OrdersAddView, OrdersDeleteView, HistoryOrdersView

app_name = 'orders'

urlpatterns = [
    path('orders/', OrdersView.as_view(), name='orders'),
    path('orders_add/', OrdersAddView.as_view(), name='orders_add'),
    path('orders_delete/<int:order_id>/', OrdersDeleteView.as_view(), name='orders_delete'),
    path('history_orders/', HistoryOrdersView.as_view(), name='history_orders'),
]

backend/cart/models.py
from django.db import models
from catalog.models import Product
from users.models import CustomUser


class Cart(models.Model):
    '''Корзина'''
    user = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        related_name='cart',
        verbose_name='Пользователь'
    )
    products = models.ForeignKey(
        Product,
        on_delete=models.PROTECT,
        related_name='cart',
        verbose_name = 'Продукты',
    )
    weight = models.FloatField(
        verbose_name = 'Вес продукта',
        default=0
    )
    price = models.FloatField(
        verbose_name='Стоимость продукта',
        default=0
    )


    class Meta:
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзины'

    def __str__(self):
        return self.products.name
    

backend/cart/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View
from cart.models import Cart
from catalog.models import Product
from django.http import JsonResponse

class CartView(View):
    """Представление для отображения корзины покупок"""

    template_name = "cart/cart.html"
    
    def get(self, request):
        """Обрабатывает GET-запрос для отображения содержимого корзины"""

        if request.user.is_authenticated:
            # Если пользователь аутентифицирован, получаем корзину из базы данных
            carts = Cart.objects.filter(user=request.user)
            # Рассчитываем общую стоимость корзины
            total_price = sum(cart.weight * cart.products.fix_price for cart in carts)
        else:
            # Если пользователь не аутентифицирован, получаем корзину из сессии
            cart = request.session.get('cart', {})
            carts = [{'product': Product.objects.get(id=product_id),
                      'weight': weight,
                      'price': weight * Product.objects.get(id=product_id).fix_price}
                      for product_id, weight in cart.items()
            ]
            # Рассчитываем общую стоимость корзины
            total_price = sum(item['price'] for item in carts)

        context = {
            "carts": carts,
            "total_price": total_price,
        }
        return render(request, self.template_name, context)

class CartAddView(View):
    """Представление для добавления продукта в корзину"""

    def post(self, request, product_id):
        """Обрабатывает POST-запрос для добавления продукта в корзину"""

        product = get_object_or_404(Product, id=product_id)
        if request.user.is_authenticated:
            # Если пользователь аутентифицирован, обновляем корзину в базе данных
            cart, created = Cart.objects.get_or_create(products=product, user=request.user)
            cart.weight += 0.5
            cart.price = cart.weight * product.fix_price
            cart.save()

            total_price = sum(item.weight * item.products.fix_price for item in Cart.objects.filter(user=request.user))
            # Общее количество товаров в корзине в навигаторе
            total_items = Cart.objects.filter(user=request.user).count()
        else:
            # Если пользователь не аутентифицирован, обновляем корзину в сессии
            cart = request.session.get('cart', {})
            if str(product_id) in cart:
                cart[str(product_id)] += 0.5
            else:
                cart[str(product_id)] = 0.5
            request.session['cart'] = cart
            request.session.modified = True

            total_price = sum(
                weight * Product.objects.get(id=int(product_id)).fix_price
                for product_id, weight in cart.items()
            )
            # Общее количество товаров в корзине в навигаторе
            total_items = len(cart)

        # Перенаправляем обратно на страницу, с которой пришел запрос
        return JsonResponse({
            "weight": cart.weight if request.user.is_authenticated else cart.get(str(product_id), 0),
            "price": cart.price if request.user.is_authenticated else cart.get(str(product_id), 0) * product.fix_price,
            "total_price": total_price,
            "total_items": total_items,  # Общее количество товаров в корзине в навигаторе
        })

class CartRemoveView(View):
    """Представление для удаления продукта из корзины"""

    def post(self, request, product_id):
        """Обрабатывает POST-запрос для удаления продукта из корзины"""

        product = get_object_or_404(Product, id=product_id)
        product_removed = False  # Флаг для удаления продукта из корзины
        is_cart_empty = False  # Флаг для проверки, пуста ли корзина
        if request.user.is_authenticated:
            # Если пользователь аутентифицирован, обновляем корзину в базе данных
            cart = Cart.objects.filter(products=product, user=request.user).first()
            if cart:
                if cart.weight > 0.5:
                    cart.weight -= 0.5
                    cart.price = cart.weight * product.fix_price
                    cart.save()
                else:
                    cart.delete()
                    product_removed = True  # Обновляем флаг при удалении продукта
            # Проверка, пуста ли корзина
            is_cart_empty = not Cart.objects.filter(user=request.user).exists()
            total_price = sum(
                item.weight * item.products.fix_price
                for item in Cart.objects.filter(user=request.user)
            )
            total_items = Cart.objects.filter(user=request.user).count()
        else:
            # Если пользователь не аутентифицирован, обновляем корзину в сессии
            cart = request.session.get('cart', {})
            if str(product_id) in cart:
                if cart[str(product_id)] > 0.5:
                    cart[str(product_id)] -= 0.5
                else:
                    del cart[str(product_id)]
                    product_removed = True  # Обновляем флаг при удалении продукта
                request.session['cart'] = cart
                request.session.modified = True

            # Проверка, пуста ли корзина
            is_cart_empty = not cart
            # Пересчитываем общую стоимость корзины для сессии
            total_price = sum(
                weight * Product.objects.get(id=int(product_id)).fix_price
                for product_id, weight in cart.items()
            )
            total_items = len(cart)

        # Возвращаем JSON-ответ с актуальными данными
        return JsonResponse({
            "weight": 0 if product_removed else (cart.weight if request.user.is_authenticated else cart.get(str(product_id), 0)),
            "price": 0 if product_removed else (cart.price if request.user.is_authenticated else cart.get(str(product_id), 0) * product.fix_price),
            "total_price": total_price,
            "total_items": total_items,  # Общее количество товаров
            "removed": product_removed,  # Указывает, что продукт удалён
            "is_cart_empty": is_cart_empty,  # Указывает, пуста ли корзина
        })

backend/cart/templates/cart/cart.html
{% extends "base.html" %}
{% load static %}
{% block title %} Корзина {% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/desktop_version/cart.css' %}">
{% endblock %}
{% block content %}
    <main>
        {% if request.user.is_authenticated %}
            <section class="list-cart-products">
                {% if not carts.exists %}
                    <div class="cart-logo">
                        <p>Ваша корзина пуста!</p>
                        <img src="{% static 'logo/cart-empty.png' %}" alt="Изображение">
                    </div>
                {% else %}
                    <p class="cart-list-products">
                        Список продуктов в корзине:
                    </p>
                    {% for cart in carts %}
                        <figure class="cart-product" data-product-id="{{ cart.products.id }}">
                            <div class="cart-product-item">
                                <img class="cart-product-img" src="{{ cart.products.image.url }}" alt="{{ cart.products.name }}">
                                <p class="cart-product-name">{{ cart.products.name }}</p>
                            </div>
                            <figcaption class="cart-product-info">
                                <form action="{% url 'cart:cart_remove' cart.products.id %}" method="post" data-product-id="{{ cart.products.id }}">
                                    {% csrf_token %}
                                    <input class="cart-product-delete" type="submit" value="➖">
                                </form>
                                <p class="cart-product-weight">{{ cart.weight }} кг</p>
                                <form action="{% url 'cart:cart_add' cart.products.id %}" method="post">
                                    {% csrf_token %}
                                    <input class="cart-product-add" type="submit" value="➕">
                                </form>
                                <p class="cart-product-price">{{ cart.price }} &#8381</p>
                            </figcaption>
                        </figure>
                    {% endfor %}
                    <div class="sum-cart-products">
                        <a href="{% url 'orders:orders' %}">
                            <button>
                                Перейти к заказу {{ total_price }} <span>&#8381</span>
                            </button>
                        </a>
                    </div>
                {% endif %}
            </section>
        {% else %}
            <section class="list-cart-products">
                {% if carts %}
                    <p class="cart-list-products">
                        Список продуктов в корзине:
                    </p>
                    {% for cart in carts %}
                        <figure class="cart-product" data-product-id="{{ cart.products.id }}">
                            <div class="cart-product-item">
                                <img class="cart-product-img" src="{{ cart.product.image.url }}" alt="{{ cart.product.name }}">
                                <p class="cart-product-name">{{ cart.product.name }}</p>
                            </div>
                            <figcaption class="cart-product-info">
                                <form action="{% url 'cart:cart_remove' cart.product.id %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="product_id" value="{{ cart.product.id }}" data-product-id="{{ cart.products.id }}">
                                    <input class="cart-product-delete" type="submit" value="➖">
                                </form>
                                <p class="cart-product-weight">{{ cart.weight }} кг</p>
                                <form action="{% url 'cart:cart_add' cart.product.id %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="product_id" value="{{ cart.product.id }}">
                                    <input class="cart-product-add" type="submit" value="➕">
                                </form>
                                <p class="cart-product-price">{{ cart.price }} &#8381</p>
                            </figcaption>
                        </figure>
                    {% endfor %}
                    <div class="sum-cart-products">
                        <a href="{% url 'orders:orders' %}">
                            <button>
                                Перейти к заказу {{ total_price }} <span>&#8381</span>
                            </button>
                        </a>
                    </div>
                {% else %}
                    <div class="cart-logo">
                        <p>Ваша корзина пуста!</p>
                        <img src="{% static 'logo/cart-empty.png' %}" alt="Изображение">
                    </div>
                {% endif %}
            </section>
        {% endif %}
    </main>
    <script src="{% static 'js/AJAX.js' %}?v=1.0.1"></script>
    <!-- Добавление параметра версии (?v=1.0.1) в URL гарантирует, что браузер загрузит свежую копию файла, игнорируя кэш. -->
{% endblock %}