backend/cart/urls.py
from django.urls import path
from .views import CartView, CartAddView, CartRemoveView

app_name = 'cart'

urlpatterns = [
    path('cart/', CartView.as_view(), name='cart'),
    path('cart_add/<int:product_id>/', CartAddView.as_view(), name='cart_add'),
    path('cart_remove/<int:product_id>/', CartRemoveView.as_view(), name='cart_remove'),
]

backend/config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('homepages/', include('homepages.urls', namespace='homepages')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = views.page_not_found
handler403 = views.csrf_failure
handler500 = views.server_error
handler400 = views.bad_request

backend/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('account/', views.AccountView.as_view(), name='account'),
    path('account_add/', views.AccountAddView.as_view(), name='account_add'),
    path('account_delete/', views.AccountDeleteView.as_view(), name='account_delete'),
    path('account_update/', views.AccountUpdateView.as_view(), name='account_update'),
]

backend/users/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.contrib.auth.validators import UnicodeUsernameValidator

class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('Email должен быть указан')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Суперпользователь должен иметь is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Суперпользователь должен иметь is_superuser=True.')

        return self.create_user(email, password, **extra_fields)

class CustomUser(AbstractBaseUser, PermissionsMixin):
    '''Пользователь'''

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    email = models.EmailField(
        verbose_name="Электронная почта",
        unique=True
    )
    first_name = models.CharField(
        max_length=15,
        verbose_name="Имя"
    )
    phone = models.CharField(
        max_length=15,
        verbose_name="Телефон"
    )
    address = models.CharField(
        max_length=50,
        verbose_name="Адрес"
    )
    image = models.ImageField(
        upload_to='users',
        null=True,
        blank=True,
        verbose_name="Изображение"
    )
    check_list = models.BooleanField(
        default=False,
        verbose_name="Согласие на обработку персональных данных"
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name="Активен"
    )
    is_staff = models.BooleanField(
        default=False,
        verbose_name="Персонал"
    )

    objects = CustomUserManager()

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.email

backend/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from .models import CustomUser


class CustomLoginForm(AuthenticationForm):
    error_messages = {
        'invalid_login': "Пожалуйста, введите правильную электронную почту и пароль. Оба поля могут быть чувствительны к регистру.",
        'inactive': "Этот аккаунт не активен.",
    }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Электронная почта'
        self.fields['password'].label = 'Пароль'


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('email',)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if CustomUser.objects.filter(email=email).exists():
            raise forms.ValidationError('Такая электронная почта уже существует.')
        return email

class CustomUserChangeForm(UserChangeForm):
    password=None
    class Meta:
        model = CustomUser
        fields = ('email', 'first_name', 'phone', 'address', 'image', 'check_list')

backend/users/views.py
from django.shortcuts import HttpResponse, render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.contrib.auth import login as auth_login, logout as auth_logout, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import CustomUser
from .forms import CustomUserCreationForm, CustomUserChangeForm, CustomLoginForm
from django.contrib.auth import get_user_model
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_decode

class LoginView(View):
    """Обрабатывает страницу входа пользователя."""
    template_name = 'users/login.html'

    def get(self, request):
        form = CustomLoginForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = CustomLoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            return redirect('users:account')
        return render(request, self.template_name, {'form': form})

class LogoutView(View):
    """Обрабатывает выход пользователя из системы."""
    def get(self, request):
        auth_logout(request)
        return render(request, 'users/logout.html')

class PasswordChangeView(LoginRequiredMixin, View):
    """Обрабатывает смену пароля пользователя."""
    template_name = 'users/password_change.html'
    
    def get(self, request):
        form = PasswordChangeForm(user=request.user)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('users:password_change_done')
        return render(request, self.template_name, {'form': form})

class PasswordChangeDoneView(LoginRequiredMixin, View):
    """Отображает страницу, подтверждающую успешную смену пароля."""
    template_name = 'users/password_change_done.html'
    
    def get(self, request):
        return render(request, self.template_name)

class PasswordResetView(View):
    """Обрабатывает запрос на сброс пароля."""
    template_name = 'users/password_reset.html'
    
    def get(self, request):
        form = PasswordResetForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = PasswordResetForm(data=request.POST)
        if form.is_valid():
            form.save(request=request, email_template_name='users/password_reset_email.html')
            return redirect('users:password_reset_done')
        return render(request, self.template_name, {'form': form})

class PasswordResetDoneView(View):
    """Отображает страницу, подтверждающую успешный запрос на сброс пароля."""
    template_name = 'users/password_reset_done.html'
    
    def get(self, request):
        return render(request, self.template_name)

class PasswordResetConfirmView(View):
    """Обрабатывает подтверждение сброса пароля по ссылке из email."""
    template_name = 'users/password_reset_confirm.html'
    
    def get(self, request, uidb64=None, token=None):
        """Отображает форму для ввода нового пароля, если токен действителен."""
        try:
            UserModel = get_user_model()
            uid = urlsafe_base64_decode(uidb64).decode()
            user = UserModel._default_manager.get(pk=uid)
            
            if default_token_generator.check_token(user, token):
                form = SetPasswordForm(user=user)
                return render(request, self.template_name, {'form': form})
            else:
                return HttpResponse('Invalid token')
        
        except (TypeError, ValueError, OverflowError, UserModel.DoesNotExist):
            return HttpResponse('Invalid link')

    def post(self, request, uidb64=None, token=None):
        """Обрабатывает отправку формы для установки нового пароля, если токен действителен."""
        try:
            UserModel = get_user_model()
            uid = urlsafe_base64_decode(uidb64).decode()
            user = UserModel._default_manager.get(pk=uid)
            
            if default_token_generator.check_token(user, token):
                form = SetPasswordForm(user=user, data=request.POST)
                if form.is_valid():
                    form.save()
                    return redirect('users:password_reset_complete')
                else:
                    return render(request, self.template_name, {'form': form})
            else:
                return HttpResponse('Invalid token')
        
        except (TypeError, ValueError, OverflowError, UserModel.DoesNotExist):
            return HttpResponse('Invalid link')

class PasswordResetCompleteView(View):
    """Отображает страницу, подтверждающую успешное завершение сброса пароля."""
    template_name = 'users/password_reset_complete.html'
    
    def get(self, request):
        return render(request, self.template_name)

class AccountView(LoginRequiredMixin, View):
    """Отображает страницу с информацией о пользователях."""
    template_name = 'users/account.html'

    def get(self, request):
        accounts = CustomUser.objects.all()
        return render(request, self.template_name, {'accounts': accounts})

class AccountAddView(View):
    """Регистрация нового пользователя."""
    template_name = 'users/account_add.html'
    
    def get(self, request):
        form = CustomUserCreationForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('users:account')
        return render(request, self.template_name, {'form': form})

class AccountDeleteView(LoginRequiredMixin, View):
    """Удаление аккаунта пользователя."""
    template_name = 'users/account_delete.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        user = request.user
        user.delete()
        return redirect(reverse_lazy('users:login'))

class AccountUpdateView(LoginRequiredMixin, View):
    """Обновление данных аккаунта пользователя."""
    template_name = 'users/account_update.html'

    def get(self, request):
        form = CustomUserChangeForm(instance=request.user)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('users:account')
        return render(request, self.template_name, {'form': form})

backend/users/templates/users/account.html
{% extends "base.html" %}
{% load static %}
{% block titel %} Личный кабинет {% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/desktop_version/account.css' %}">
{% endblock %}
{% block content %}
    <figure class="account">
        {% if not user.image %}
            <img class="account-logo" src="{% static 'logo/block-user.png' %}" alt="Изображение">
        {% else %}
            <img class="account-img" src="{{ user.image.url }}" alt="{{ first_name.name }}">
        {% endif %}

        {% if not user.first_name %}
            <h1>Имя не заполнено</h1>
        {% else %}
            <h1>{{ user.first_name }}</h1>
        {% endif %}

        <div>
            <p>{{ user.email }}</p>
        </div>
        <div>
            <p>************</p>
        </div>
        <div>
            {% if not user.phone %}
                <p>Телефон не заполнен</p>
            {% else %}
                <p>{{ user.phone }}</p>
            {% endif %}
        </div>
        <div>
            {% if not user.address %}
                <p>Адрес не заполнен</p>
            {% else %}
                <p>{{ user.address }}</p>
            {% endif %}
        </div>
        <a href="{% url 'users:account_update' %}">
            <button>
                Изменить данные аккаунта
            </button>
        </a>
        <a href="{% url 'users:password_change' %}">
            <button>
                Изменить пароль
            </button>
        <a href="{% url 'users:logout' %}">
            <button>
                Выйти из аккаунта
            </button>
        </a>
        <a href="{% url 'users:account_delete' %}">
            <button>
                Удалить аккаунта
            </button>
        </a>
    </figure>
{% endblock %}

backend/users/templates/users/account_add.html
{% extends "base.html" %}
{% load static %}
{% block title %} Регистрация {% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/desktop_version/login.css' %}">
{% endblock %}
{% block content %}
<div class="login-container">
    <div class="login-item">
        <p>Регистрация</p>
        <form method="post" action="{% url 'users:account_add' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-registration">
                {% for field in form %}
                    {{ field.label_tag }}
                    {{ field }}
                    
                    {% if field.errors %}
                        <div class="errors">{{ field.errors }}</div>
                    {% endif %}
                {% endfor %}
                <p>
                    - Пароль не должен быть слишком похож на другую вашу личную информацию.<br>
                    - Ваш пароль должен содержать как минимум 8 символов.<br>
                    - Пароль не должен быть слишком простым и распространенным.<br>
                    - Пароль не может состоять только из цифр.<br>
                </p>
            </div>
            <div class="login-button">
                <button type="submit">Зарегистрироваться</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

backend/users/templates/users/account_delete.html
{% extends "base.html" %}
{% load static %}
{% block title %} Удаление аккаунта {% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/desktop_version/login.css' %}">
{% endblock %}
{% block content %}
<div class="login-container">
    <form method="post" action="{% url 'users:account_delete' %}">
        {% csrf_token %}
        <div class="account-delete">
            <p>Вы уверены, что хотите удалить свой аккаунт?</p>
            <p style="color: red;">{{ user.email }}</p>
            <div class="login-button">
                <button type="submit">Удалить</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

backend/users/templates/users/account_update.html
{% extends "base.html" %}
{% load static %}
{% block title %} Обновление аккаунта {% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/desktop_version/login.css' %}">
{% endblock %}
{% block content %}
<div class="login-container-account">
    <div class="login-item">
        <p>Изменить данные</p>
        <form method="post" action="{% url 'users:account_update' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                {{ field.label_tag }}
                {{ field }}
                {% if field.errors %}
                    <div class="errors">{{ field.errors }}</div>
                {% endif %}
            {% endfor %}
            <div class="login-button">
                <button type="submit">Сохранить</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

backend/users/templates/users/login.html
{% extends "base.html" %}
{% load static %}
{% block title %} Вход {% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/desktop_version/login.css' %}">
{% endblock %}
{% block content %}
<div class="login-container">
    <div class="login-item">
        <p>Вход</p>
        <form method="post" action="{% url 'users:login' %}">
            {% csrf_token %}
            {% for field in form %}
                {{ field.label_tag }}
                {{ field }}
            {% endfor %}
            <div class="errors">
                {% for error in form.non_field_errors %}
                    {{ error }}
                {% endfor %}
            </div>
            <div class="login-links">
                <p><a href="{% url 'users:account_add' %}">Регистрация</a></p>
                <p><a href="{% url 'users:password_reset' %}">Забыли пароль?</a></p>
            </div>
            <div class="login-button">
                <button type="submit">Войти</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

backend/users/templates/users/logout.html
{% extends "base.html" %}
{% load static %}
{% block titel %} Вход {% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/desktop_version/login.css' %}">
{% endblock %}
{% block content %}
    <div class="logout">
        <p>Вы вышли из аккаунта</p>
    </div>
{% endblock %}

backend/users/templates/users/password_change.html
{% extends "base.html" %}
{% load static %}
{% block title %} Изменение пароля {% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/desktop_version/login.css' %}">
{% endblock %}
{% block content %}
<div class="login-container">
    <div class="login-item">
        <form method="post" action="{% url 'users:password_change' %}">
            {% csrf_token %}
            <div class="form-password-change">
                {% for field in form %}
                    {{ field.label_tag }}
                    {{ field }}
                    {% if field.errors %}
                        <div class="errors">{{ field.errors }}</div>
                    {% endif %}
                {% endfor %}
                <p>
                    - Пароль не должен быть слишком похож на другую вашу личную информацию.<br>
                    - Ваш пароль должен содержать как минимум 8 символов.<br>
                    - Пароль не должен быть слишком простым и распространенным.<br>
                    - Пароль не может состоять только из цифр.<br>
                </p>
                <div class="login-links-password_change">
                    <p><a href="{% url 'users:password_reset' %}">Забыли пароль?</a></p>
                </div>
            </div>
            <div class="login-button">
                <button type="submit">Изменить пароль</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

backend/users/templates/users/password_change_done.html
{% extends "base.html" %}
{% load static %}
{% block title %} Пароль изменен {% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/desktop_version/login.css' %}">
{% endblock %}
{% block content %}
<div class="login-container">
    <div class="message-email">
        <p>Ваш пароль был успешно изменен.</p>
    </div>
</div>
{% endblock %}

backend/users/templates/users/password_reset.html
{% extends "base.html" %}
{% load static %}
{% block title %} Восстановление пароля {% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/desktop_version/login.css' %}">
{% endblock %}
{% block content %}
<div class="login-container">
    <div class="login-item">
        <p>Восстановить пароль</p>
        <form method="post" action="{% url 'users:password_reset' %}">
            {% csrf_token %}
            {{ form.email.label_tag }}
            {{ form.email }}
            <div class="login-button">
                <button type="submit">Отправить пароль</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

backend/users/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% load static %}
{% block title %} Пароль изменен по ссылке {% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/desktop_version/login.css' %}">
{% endblock %}
{% block content %}
<div class="login-container">
    <div class="message-email">
        <p>Ваш пароль был успешно изменен. Теперь вы можете <a href="{% url 'users:login' %}">войти</a> с новым паролем.</p>
    </div>
</div>
{% endblock %}

backend/users/templates/users/password_reset_confirm.html
<!-- Изменение пароля по ссылке -->
{% extends "base.html" %}
{% load static %}
{% block title %} Изменение пароля по ссылке {% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/desktop_version/login.css' %}">
{% endblock %}
{% block content %}
<div class="login-container">
    <div class="login-item">
        <form method="post" action="">
            {% csrf_token %}
            <div class="form-password-change">
                {% for field in form %}
                    {{ field.label_tag }}
                    {{ field }}
                    {% if field.errors %}
                        <div class="errors">{{ field.errors }}</div>
                    {% endif %}
                {% endfor %}
                <p>
                    - Пароль не должен быть слишком похож на другую вашу личную информацию.<br>
                    - Ваш пароль должен содержать как минимум 8 символов.<br>
                    - Пароль не должен быть слишком простым и распространенным.<br>
                    - Пароль не может состоять только из цифр.<br>
                </p>
            </div>
            <div class="login-button">
                <button type="submit">Изменить пароль</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}
 

backend/users/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load static %}
{% block title %} Ссылка на восстановление отправлена {% endblock %}
{% block content %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/desktop_version/login.css' %}">
{% endblock %}
<div class="login-container">
    <div class="message-email">
        <p>Ссылка на восстановление пароля была отправлена на ваш email.</p>
    </div>
</div>
{% endblock %}

backend/users/templates/users/password_reset_email.html
{% load i18n %}
{% blocktrans %}
Здравствуйте,
{% endblocktrans %}
{% blocktrans %}
Вы получили это письмо, потому что запросили сброс пароля для своей учетной записи.
{% endblocktrans %}
{% blocktrans %}
Перейдите по ссылке ниже, чтобы установить новый пароль:
{% endblocktrans %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token|safe %}
{% blocktrans %}
Если вы не запрашивали сброс пароля, просто проигнорируйте это письмо.
{% endblocktrans %}
{% blocktrans %}
С уважением,
Команда сайта
{% endblocktrans %}