backend/cart/urls.py
from django.urls import path
from .views import CartView, CartAddView, CartRemoveView

app_name = 'cart'

urlpatterns = [
    path('cart/', CartView.as_view(), name='cart'),
    path('cart_add/<int:product_id>/', CartAddView.as_view(), name='cart_add'),
    path('cart_remove/<int:product_id>/', CartRemoveView.as_view(), name='cart_remove'),
]

backend/catalog/urls.py
from django.urls import path
from .views import ProductListView

app_name = 'catalog'

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
]

backend/config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('homepages/', include('homepages.urls', namespace='homepages')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = views.page_not_found
handler403 = views.csrf_failure
handler500 = views.server_error
handler400 = views.bad_request

backend/homepages/urls.py
from django.urls import path
from .views import AboutUsView, DeliveryView, PromotionsView, QualityAssuranceView

app_name = 'homepages'

urlpatterns = [
    path('about_us/', AboutUsView.as_view(), name='about_us'),
    path('delivery/', DeliveryView.as_view(), name='delivery'),
    path('promotions/', PromotionsView.as_view(), name='promotions'),
    path('quality_assurance/', QualityAssuranceView.as_view(), name='quality_assurance'),
]

backend/orders/urls.py
from django.urls import path
from .views import OrdersView, OrdersAddView, OrdersDeleteView, HistoryOrdersView

app_name = 'orders'

urlpatterns = [
    path('orders/', OrdersView.as_view(), name='orders'),
    path('orders_add/', OrdersAddView.as_view(), name='orders_add'),
    path('orders_delete/<int:order_id>/', OrdersDeleteView.as_view(), name='orders_delete'),
    path('history_orders/', HistoryOrdersView.as_view(), name='history_orders'),
]

backend/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('account/', views.AccountView.as_view(), name='account'),
    path('account_add/', views.AccountAddView.as_view(), name='account_add'),
    path('account_delete/', views.AccountDeleteView.as_view(), name='account_delete'),
    path('account_update/', views.AccountUpdateView.as_view(), name='account_update'),
]

backend/catalog/models.py
from django.db import models

class Product(models.Model):
    '''Продукт'''
    name = models.CharField(
        max_length=256,
        verbose_name='Название продукта'
    )
    product_type = models.CharField(
        max_length=128,
        verbose_name='Тип продукта',
        null=True,
        blank=True
    )
    category = models.CharField(
        max_length=128,
        verbose_name='Категория продукта',
        null=True,
        blank=True
    )
    image = models.ImageField(
        verbose_name='Изображение продукта',
        upload_to='products',
        null=True,
        blank=True
    )
    fix_price = models.FloatField(
        verbose_name='Фиксированная цена за кг продукта',
        null=True,
        blank=True
    )
    stock = models.IntegerField(
        verbose_name='Остаток продукта в кг',
        null=True,
        blank=True
    )

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
    
    def __str__(self):
        return self.name

backend/catalog/views.py
from django.shortcuts import render
from django.views import View
from .models import Product
from cart.models import Cart
from collections import defaultdict

class ProductListView(View):
    """Представление для отображения списка продуктов по категориям"""

    template_name = "catalog/product_list.html"
    
    def get(self, request):
        """Обрабатывает GET-запрос для отображения продуктов по категориям"""

        # Получаем продукты и группируем их по категориям
        products = Product.objects.all()
        products_by_category = defaultdict(list)
        for product in products:
            products_by_category[product.category].append(product)
        
        if request.user.is_authenticated:
            cart_products = Cart.objects.filter(user=request.user)
            products_in_cart = cart_products.values_list('products_id', flat=True)
        else:
            cart = request.session.get('cart', {})
            products_in_cart = cart.keys()
            cart_products = [{'products_id': int(product_id), 'weight': weight} for product_id, weight in cart.items()]

        context = {
            "products_by_category": products_by_category.items(),  # Здесь важно вызвать `.items()`
            "products_in_cart": products_in_cart,
            "cart_products": cart_products,
        }
        return render(request, self.template_name, context)

backend/catalog/templates/includes/footer.html
{% load static %}
<footer>
    <div class="footer-content">
        <div class="footer-content-item">
            <div class="contact-item">
                <a href="{% url 'homepages:about_us' %}" class="contact-item-info">
                    <img class="footer-logo" src="{% static 'logo/info.png' %}" alt="">
                    О нас
                </a>
                <a href="{% url 'homepages:delivery' %}" class="contact-item-info">
                    <img class="footer-logo" src="{% static 'logo/delivery.png' %}" alt="">
                    Доставка
                </a>
                <a href="{% url 'homepages:promotions' %}"class="contact-item-info">
                    <img class="footer-logo" src="{% static 'logo/promotions.png' %}" alt="">
                    Акции
                </a>
                <a href="{% url 'homepages:quality_assurance' %}"class="contact-item-info">
                    <img class="footer-logo" src="{% static 'logo/shield.png' %}" alt="">
                    Гарантия качества
                </a>
            </div>
            <div class="requisites-item">
                <h1>Контакты:</h1>
                <a href="https://t.me/romanburov89"><img class="contact-item-message" src="{% static 'logo/telegram.png' %}"alt="Telegram"></a>
                <a href="https://api.whatsapp.com/send?phone=79046484137&text=Привет!"><img class="contact-item-message" src="{% static 'logo/whatsapp.png' %}"alt="WhatsApp"></a>
                <a href="tel:+79046484137"><img class="contact-item-message" src="{% static 'logo/phone-call.png' %}"alt="Phone-call"></a>
            </div>
        </div>
        <div class="footer-content-item-adaptiv">
            <img class="footer-logo-close" src="{% static 'logo/close.png' %}" alt="">
            <img class="footer-logo-open" src="{% static 'logo/menu-open.png' %}" alt="">
        </div>
        <div class="footer-menu">
            <img class="footer-menu-logo" src="{% static 'logo/tomato.png' %}" alt="">
            <p>Mr-Tomato</p>
        </div>
    </div>
</footer>
<script src="{% static 'js/footer.js' %}"></script>

backend/catalog/templates/includes/nav.html
{% load static %}
<nav>
    <div class="navigation">
        <div class="navigation-menu">
            <a href="{% url 'catalog:product_list' %}">
                <button class="navigation-btn">
                    <img class="navigation-logo" src="{% static 'logo/fruit.png' %}" alt=""> 
                    <p>Каталог</p>
                </button>
            </a>
            <a href="{% url 'cart:cart' %}">
                <button class="navigation-btn">
                    <img class="navigation-logo" src="{% static 'logo/shopping-cart.png' %}" alt=""> 
                    <p>Корзина</p>
                    <span class="total-items-cart">{{ total_items }}</span>
                </button>
            </a>
            <a href="{% url 'orders:orders' %}">
                <button class="navigation-btn">
                    <img class="navigation-logo" src="{% static 'logo/groceries.png' %}" alt="">
                    <p>Заказ</p>
                </button>
            </a>
            <a href="{% url 'orders:history_orders' %}">
                <button class="navigation-btn">
                    <img class="navigation-logo" src="{% static 'logo/receipt.png' %}" alt="">
                    <p>История</p>
                </button>
            </a>
        </div>
        <div class="navigation-login">
            {% if user.is_authenticated %}
            <a href="{% url 'users:account' %}">
                <button class="navigation-btn">
                    <img class="navigation-logo" src="{% static 'logo/user.png' %}" alt="">
                    <p>Аккаунт</p>
                </button>
            </a>
            {% else %}
            <a href="{% url 'users:login' %}">
                <button class="navigation-btn">
                    <img class="navigation-logo" src="{% static 'logo/log-in.png' %}" alt="">
                    <p>Вход</p>
                </button>
            </a>
            {% endif %}
        </div>
    </div>
</nav>