backend/cart/urls.py
from django.urls import path
from .views import CartView, CartAddView, CartRemoveView

app_name = 'cart'

urlpatterns = [
    path('cart/', CartView.as_view(), name='cart'),
    path('cart_add/<int:product_id>/', CartAddView.as_view(), name='cart_add'),
    path('cart_remove/<int:product_id>/', CartRemoveView.as_view(), name='cart_remove'),
]

backend/config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('homepages/', include('homepages.urls', namespace='homepages')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = views.page_not_found
handler403 = views.csrf_failure
handler500 = views.server_error
handler400 = views.bad_request

backend/orders/urls.py
from django.urls import path
from .views import OrdersView, OrdersAddView, OrdersDeleteView, HistoryOrdersView

app_name = 'orders'

urlpatterns = [
    path('orders/', OrdersView.as_view(), name='orders'),
    path('orders_add/', OrdersAddView.as_view(), name='orders_add'),
    path('orders_delete/<int:order_id>/', OrdersDeleteView.as_view(), name='orders_delete'),
    path('history_orders/', HistoryOrdersView.as_view(), name='history_orders'),
]

backend/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('account/', views.AccountView.as_view(), name='account'),
    path('account_add/', views.AccountAddView.as_view(), name='account_add'),
    path('account_delete/', views.AccountDeleteView.as_view(), name='account_delete'),
    path('account_update/', views.AccountUpdateView.as_view(), name='account_update'),
]

backend/orders/models.py
from django.db import models
from users.models import CustomUser


class Order(models.Model):
    '''Заказ'''
    ORDER_STATUS_CHOICES = (
        ('waiting', 'Ожидание доставки'),
        ('delivered', 'Доставлено'),
    )
    user = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        related_name='order',
        verbose_name = 'Пользователь',
    )
    name = models.CharField(
        max_length=20,
        verbose_name='Имя',
        null=True,
        blank=True,
    )
    phone = models.CharField(
        max_length=16,
        verbose_name='Телефон',
        null=True,
        blank=True,
    )
    address = models.CharField(
        max_length=50,
        verbose_name='Адрес',
        null=True,
        blank=True,
    )
    check_list = models.BooleanField(
        verbose_name='Согласие на обработку персональных данных',
        null=True,
        blank=True,
    )
    time = models.DateTimeField(
        verbose_name='Дата и время доставки',
        null=True,
        blank=True,
    )
    status = models.CharField(
        max_length=10,
        choices=ORDER_STATUS_CHOICES,
        default='waiting',
        verbose_name='Статус заказа',
    )
    delivery_price = models.FloatField(
        verbose_name='Цена за доставку',
        default=0
    )
    total_price = models.FloatField(
        verbose_name='Итоговая цена',
        default=0
    )
    created_at = models.DateTimeField(
        verbose_name='Дата создания',
        auto_now_add=True
    )

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return f'Заказ {self.id}'


class OrderItem(models.Model):
    '''Корзина заказа'''
    order = models.ForeignKey(
        Order,
        on_delete = models.CASCADE,
        related_name='order_item',
        verbose_name = 'Данные заказа',
    )
    product_name = models.CharField(
        max_length=256,
        verbose_name='Название продукта',
        null=True,
    )
    product_weight = models.FloatField(
        verbose_name='Вес продукта',
        default=0
    )
    product_price = models.FloatField(
        verbose_name='Цена продукта',
        default=0
    )
    product_image = models.ImageField(
        verbose_name = 'Изображение продукта',
        null=True, 
        blank=True,
    )

    class Meta:
        verbose_name = 'Корзина заказа'
        verbose_name_plural = 'Корзина заказов'

    def __str__(self):
        return f'Корзина заказа {self.id}'

backend/orders/forms.py
from django import forms
from django.utils import timezone
import datetime
import pytz
from .models import Order


def get_min_time():
    moscow_tz = pytz.timezone('Europe/Moscow')
    min_time = timezone.now().astimezone(moscow_tz) + datetime.timedelta(hours=1)
    return min_time.strftime('%Y-%m-%dT%H:%M')


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['id', 'name', 'phone', 'address', 'time', 'check_list']
        widgets = {
            'name': forms.TextInput(attrs={
                'placeholder': 'Введите ваше имя',
                'required': 'required'
            }),
            'phone': forms.TextInput(attrs={
                'placeholder': '+7 (***) ***-**-**',
                'required': 'required',
                'pattern': r'\+7\(\d{3}\)\d{3}-\d{2}-\d{2}',
                'title': 'Введите номер телефона в формате +7(XXX)XXX-XX-XX',
            }),
            'address': forms.TextInput(attrs={
                'placeholder': 'Город, улица, дом, квартира',
                'required': 'required'
            }),
            'time': forms.DateTimeInput(attrs={
                'type': 'datetime-local',
                'placeholder': 'Выберите дату и время',
                'required': 'required',
                'min': get_min_time(),
            }),
            'check_list': forms.CheckboxInput(attrs={
                'required': 'required'
            }),
        }

    def clean_time(self):
        selected_time = self.cleaned_data['time']
        moscow_tz = pytz.timezone('Europe/Moscow')
        min_time = timezone.now().astimezone(moscow_tz) + datetime.timedelta(hours=1)
        if selected_time < min_time:
            raise forms.ValidationError(f'Дата и время доставки не могут быть раньше {min_time.strftime("%Y-%m-%d %H:%M")}')
        return selected_time

backend/orders/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from cart.models import Cart
from .models import Order, OrderItem
from catalog.models import Product
from .forms import OrderForm
from .telegram_message import send_telegram_message_sync
from decouple import config

class OrdersView(View):
    """Представление для отображения заказа покупок"""
    template_name = 'orders/orders.html'

    def get(self, request):
        """Обрабатывает GET-запрос для отображения текущей корзины пользователя"""
        if request.user.is_authenticated:
            # Если пользователь аутентифицирован, получаем корзину из базы данных
            carts = Cart.objects.filter(user=request.user)
            total_price = sum(cart.price for cart in carts)
        else:
            # Если пользователь не аутентифицирован, получаем корзину из сессии
            cart = request.session.get('cart', {})
            carts = [{'products': Product.objects.get(id=product_id), 'weight': weight, 'price': weight * Product.objects.get(id=product_id).fix_price} for product_id, weight in cart.items()]
            total_price = sum(item['price'] for item in carts)
        
        delivery_price = 0 if total_price >= 1500 else 300
        forms = OrderForm()
        context = {
            "forms": forms,
            "carts": carts,
            "total_price": total_price,
            "delivery_price": delivery_price,
        }
        return render(request, self.template_name, context)

class OrdersAddView(View):
    """Представление для создания заказа покупок"""
    template_name = 'orders/orders-history.html'

    def post(self, request):
        """Обрабатывает POST-запрос для создания нового заказа"""
        if not request.user.is_authenticated:
            # Если пользователь не аутентифицирован, отображаем сообщение об ошибке
            return self._render_error_message(request, "Для создания и сохранение истории ваших заказов необходимо зарегистрироваться.")
        
        form = OrderForm(request.POST)
        if not form.is_valid():
            # Если форма заказа не валидна, отображаем сообщение об ошибке
            return self._render_error_message(request, "Неверные данные формы.")

        # Создаем заказ, элементы заказа и обновляем цены
        order = self._create_order(form, request.user)
        self._create_order_items(order, request.user)
        self._update_order_prices(order)
        self._send_order_notification(order)

        # Удаляем все корзины пользователя после успешного создания заказа
        Cart.objects.filter(user=request.user).delete()
        return redirect('orders:history_orders')

    def _create_order(self, form, user):
        """Создает и сохраняет заказ"""
        order = form.save(commit=False)
        order.user = user
        order.save()
        return order

    def _create_order_items(self, order, user):
        """Создает элементы заказа на основе корзины пользователя"""
        carts = Cart.objects.filter(user=user)
        for cart in carts:
            OrderItem.objects.create(
                order=order,
                product_image=cart.products.image,
                product_name=cart.products.name,
                product_weight=cart.weight,
                product_price=cart.price
            )

    def _update_order_prices(self, order):
        """Обновляет общую стоимость заказа и стоимость доставки"""
        order_items = OrderItem.objects.filter(order=order)
        order_total_price = sum(item.product_price for item in order_items)
        delivery_price = 0 if order_total_price >= 1500 else 300
        order.total_price = order_total_price
        order.delivery_price = delivery_price
        order.save()

    def _send_order_notification(self, order):
        """Отправляет уведомление о новом заказе через Telegram"""
        order_items = OrderItem.objects.filter(order=order)
        message = f'***** Новый заказ создан! *****\n\n'
        message += f'Имя: {order.name}\n'
        message += f'Телефон: {order.phone}\n'
        message += f'Адрес: {order.address}\n'
        message += f'Дата и время доставки: {order.time}\n\n'
        message += f'Список продуктов:\n'
        for item in order_items:
            message += f'{item.product_name} - {item.product_weight} кг - {item.product_price} руб\n\n'
        message += f'Итоговая стоимость: {order.total_price}\n'
        message += f'Стоимость доставки: {order.delivery_price}\n'

        # Использование ID чатов из .env
        send_telegram_message_sync(config('TELEGRAM_CHAT_IDS').split(','), message)

    def _render_error_message(self, request, message):
        """Отображает сообщение об ошибке пользователю"""
        context = {'message': message}
        return render(request, self.template_name, context)

class OrdersDeleteView(LoginRequiredMixin, View):
    """Представление для удаление заказа покупок"""

    def post(self, request, order_id):
        """Обрабатывает POST-запрос для удаления заказа"""
        order = get_object_or_404(Order, id=order_id, user=request.user)
        order.delete()
        return redirect('orders:history_orders')

class HistoryOrdersView(View):
    """Представление для отображения истории заказа покупок"""
    template_name = 'orders/orders-history.html'

    def get(self, request):
        """Обрабатывает GET-запрос для отображения истории заказов пользователя"""
        if request.user.is_authenticated:
            # Если пользователь аутентифицирован, получаем историю заказов из базы данных
            history_orders = Order.objects.filter(user=request.user).order_by('-created_at')
            context = {'history_orders': history_orders}
        else:
            # Если пользователь не аутентифицирован, отображаем сообщение о необходимости регистрации
            message = "Для просмотра истории заказов необходимо зарегистрироваться."
            context = {'message': message}
        return render(request, self.template_name, context)

backend/orders/templates/orders/orders-history.html
{% extends "base.html" %}
{% load static %}
{% block title %}История заказов{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/desktop_version/orders-history.css' %}">
{% endblock %}
{% block content %}
    <main>
        {% if user.is_authenticated %}
            {% if not history_orders.exists %}
                <div class="order-history-logo">
                    <p>Вы ничего не заказали!</p>
                    <img src="{% static 'logo/cart-empty.png' %}" alt="Изображение">
                </div>
            {% else %}
            <div class="list-order-history-products">
                {% for order in history_orders %}
                <p class="order-history-list-products">Дата заказа {{ order.created_at }}</p>
                    <div class="order-history-info">
                        <p> Дата и время доставки: <span>{{ order.time }}</span></p>
                        <p> Статус заказа: <span>{{ order.get_status_display }}</span></p>
                        <p> Имя: <span>{{ order.name }}</span></p>
                        <p> Телефон: <span>{{ order.phone }}</span></p>
                        <p> Адрес: <span>{{ order.address }}</span></p>
                    </div>
                    <div class="order-history-total-price">
                        <p>Итог: {{ order.total_price }} <span>&#8381</span></p>
                        <p>Доставка: {{ order.delivery_price }} <span>&#8381</span></p>
                    </div>
                    {% for order_item in order.order_item.all %}
                        <figure class="order-history-product">
                            <div class="order-history-product-item">
                                <img class="order-history-product-img" src="{{ order_item.product_image.url }}" alt="{{ order_item.product_name }}">
                                <p class="order-history-product-name">{{ order_item.product_name }}</p>
                            </div>
                            <figcaption class="order-history-product-info">
                                <p class="order-history-product-weight">{{ order_item.product_weight }} кг</p>
                                <p class="order-history-product-price">{{ order_item.product_price }} &#8381</p>
                            </figcaption>
                        </figure>
                    {% endfor %}
                    {% if order.status == 'waiting' %}
                        <form action="{% url 'orders:orders_delete' order.id %}" method="post">
                            {% csrf_token %}
                            <input class="order-delete" type="submit" value="Удалить заказ">
                        </form>
                    {% endif %}
                {% endfor %}
            </div>
            {% endif %}
        {% else %}
            <div class="order-history-registration">
                <p>{{ message }}</p>
                <p><a href="{% url 'users:account_add' %}">Зарегистрироваться</a></p>
            </div>
        {% endif %}
    </main>
{% endblock %}

backend/orders/templates/orders/orders.html
{% extends "base.html" %}
{% load static %}
{% block title %}Заказ{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/desktop_version/orders.css' %}">
{% endblock %}
{% block content %}
    <main>
        {% if carts %}
        <div class="list-order-products">
            <p class="order-list-products">Список продуктов в заказе:</p>
            {% for cart in carts %}
                <figure class="order-product">
                    <div class="order-product-item">
                        <img class="order-product-img" src="{{ cart.products.image.url }}" alt="{{ cart.products.name }}">
                        <p class="order-product-name">{{ cart.products.name }}</p>
                    </div>
                    <figcaption class="order-product-info">
                        <p class="order-product-weight">{{ cart.weight }} кг</p>
                        <p class="order-product-price">{{ cart.price }} &#8381</p>
                    </figcaption>
                </figure>
            {% endfor %}    
            <div class="order-total-price">
                <h1>Итог: {{ total_price }} <span>&#8381</span></h1>
                <h1>Доставка: {{ delivery_price }} <span>&#8381</span></h1>
                <p>Стоимость бесплатной доставки от 1500 рублей.
                Стоимоть доставки зависит от цены заказа и от адреса.
                Ознакомиться подробнее.
                </p>
            </div>
            <form action="{% url 'orders:orders_add' %}" method="post">
                {% csrf_token %}
                <div class="order-info-pay">
                    <div class="order-info">
                        <p>Отправить данные заказа</p>
                        <label>Имя пользователя</label>
                        {{ forms.name }}
                        <label>Телефон</label>
                        {{ forms.phone }}
                        <label>Адрес доставки</label>
                        {{ forms.address }}
                        <label>Дата и время доставки</label>
                        {{ forms.time }}
                        <div class="order-info-check-list">
                            {{ forms.check_list }}
                            <label>Согласие на обработку персональных данных</label>
                        </div>
                    </div>
                    <div class="order-pay">
                        <input class="order-pay-button" type="submit" value="Оформить заказ">
                    </div>
                </div>
            </form>
        </div>
        {% else %}
        <div class="order-logo">
            <p>Ваша корзина пуста!</p>
            <img src="{% static 'logo/cart-empty.png' %}" alt="Изображение">
        </div>
        {% endif %}
    </main>
    <script src="{% static 'js/order.js' %}"></script>
{% endblock %}